# --- Base de données (Locale) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/sbems_db
spring.datasource.username=postgres
spring.datasource.password=ahmed
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Kafka (Docker via Port Externe) ---
# On utilise 9094 car Spring Boot tourne sur Windows, pas dans Docker
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=sbems-backend-group
spring.kafka.consumer.auto-offset-reset=earliest
# On dit à Kafka qu'on reçoit du JSON, mais on le lira en String pour le parser nous-même (plus sûr au début)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer